// src/components/ui/tags-input.tsx
"use client";

import { useState } from "react";
import { X } from "lucide-react";
import { cn } from "@/lib/utils";

interface TagsInputProps {
  value: string[];
  onChange: (tags: string[]) => void;
  placeholder?: string;
  max?: number;
  suggestions?: string[];
  disabled?: boolean;
}

export function TagsInput({
  value,
  onChange,
  placeholder,
  max = 10,
  suggestions = [],
  disabled = false,
}: TagsInputProps) {
  const [draft, setDraft] = useState("");

  const addTag = (raw: string) => {
    const tag = raw.trim().toLowerCase().replace(/^#/, "");
    if (!tag || value.includes(tag) || value.length >= max || disabled) return;
    onChange([...value, tag]);
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Enter" || e.key === "," || e.key === " ") {
      e.preventDefault();
      if (draft.trim()) {
        addTag(draft);
        setDraft("");
      }
    } else if (e.key === "Backspace" && !draft && value.length) {
      onChange(value.slice(0, -1));
    }
  };

  const filtered = suggestions.filter(
    (s) => !value.includes(s) && s.toLowerCase().includes(draft.toLowerCase()),
  );

  return (
    <div
      className={cn(
        "relative flex min-h-10 flex-wrap items-center gap-1.5 rounded-lg border border-input bg-background px-2 py-1.5 transition-colors focus-within:border-ring focus-within:ring-3 focus-within:ring-ring/50",
        disabled && "opacity-60",
      )}
    >
      {value.map((tag) => (
        <span
          key={tag}
          className="inline-flex items-center gap-1 rounded-full border border-border bg-muted/50 px-2 py-0.5 text-xs font-medium text-foreground/85"
        >
          #{tag}
          {!disabled && (
            <button
              type="button"
              aria-label={`Hapus tag ${tag}`}
              onClick={() => onChange(value.filter((t) => t !== tag))}
              className="text-muted-foreground transition-colors hover:text-foreground"
            >
              <X className="h-3 w-3" />
            </button>
          )}
        </span>
      ))}

      {!disabled && (
        <input
          value={draft}
          onChange={(e) => setDraft(e.target.value)}
          onKeyDown={handleKeyDown}
          onBlur={() => {
            if (draft.trim()) addTag(draft);
            setDraft("");
          }}
          placeholder={value.length ? "" : placeholder}
          className="min-w-[120px] flex-1 bg-transparent px-1 py-0.5 text-sm outline-none placeholder:text-muted-foreground"
        />
      )}

      {draft && filtered.length > 0 && (
        <div className="absolute z-10 mt-1 max-h-40 w-56 overflow-auto rounded-lg border border-border bg-popover p-1 shadow-lg">
          {filtered.slice(0, 8).map((s) => (
            <button
              key={s}
              type="button"
              onMouseDown={(e) => {
                e.preventDefault();
                addTag(s);
                setDraft("");
              }}
              className="block w-full rounded-md px-2 py-1 text-left text-xs text-foreground/85 transition-colors hover:bg-accent"
            >
              #{s}
            </button>
          ))}
        </div>
      )}
    </div>
  );
}

// src/components/ui/tags-input/TagsInput.vue
<script setup lang="ts">
import { computed } from "vue";
import {
  TagsInputRoot,
  TagsInputInput,
  TagsInputItem,
  TagsInputItemText,
  TagsInputClear,
} from "reka-ui";
import { X } from "lucide-vue-next";

const model = defineModel<string[]>();

interface Props {
  placeholder?: string;
  suggestions?: string[];
  allowNew?: boolean;
  max?: number;
  id?: string;
  name?: string;
  required?: boolean;
  /** string or RegExp accepted by reka-ui delimiter */
  delimiter?: string | RegExp;
  disabled?: boolean;
}
const props = withDefaults(defineProps<Props>(), {
  placeholder: "Ketik & tekan Enter/spasi…",
  suggestions: () => [],
  allowNew: true,
  max: 0,
  delimiter: ",",
  disabled: false,
});

const emit = defineEmits<{
  (e: "add", value: string): void;
  (e: "remove", value: string): void;
}>();

const delimiter = computed(() => {
  const d = props.delimiter;
  if (typeof d === "string") {
    if (d.length === 1) return new RegExp(`[${d}]`);
    return d;
  }
  return d;
});

const canAddMore = computed(() =>
  props.max > 0 ? (model.value?.length ?? 0) < props.max : true,
);
const inputDisabled = computed(() => props.disabled || !canAddMore.value);

function tags(): string[] {
  return model.value ?? [];
}

function onAdd(value: string) {
  const v = value.trim();
  if (!v) return;
  if (!canAddMore.value) return;
  if (tags().includes(v)) return;
  if (!props.allowNew && !(props.suggestions || []).includes(v)) return;
  model.value = [...tags(), v];
  emit("add", v);
}

function onRemove(value: string) {
  model.value = tags().filter((t) => t !== value);
  emit("remove", value);
}
</script>

<template>
  <TagsInputRoot
    v-model="model"
    :delimiter="delimiter"
    :max="max"
    :name="name"
    :required="required"
    :disabled="disabled"
    @add-tag="onAdd"
    @remove-tag="onRemove"
    class="flex flex-wrap items-center gap-1.5 rounded-md border border-input bg-background px-2 py-1.5 text-sm transition-colors focus-within:ring-2 focus-within:ring-ring focus-within:ring-offset-2 focus-within:ring-offset-background disabled:cursor-not-allowed disabled:opacity-50"
  >
    <template v-if="tags().length">
      <TagsInputItem
        v-for="t in tags()"
        :key="t"
        :value="t"
        class="m-0.5 inline-flex items-center gap-1 rounded-md bg-secondary px-2.5 py-1 text-xs font-medium text-secondary-foreground"
      >
        <TagsInputItemText />
        <button
          type="button"
          @click.stop="onRemove(t)"
          class="inline-flex items-center justify-center rounded-full p-0.5 hover:bg-secondary-foreground/20"
          :aria-label="`Hapus ${t}`"
        >
          <X class="h-3 w-3" />
        </button>
      </TagsInputItem>
    </template>

    <TagsInputInput
      :placeholder="canAddMore ? placeholder : 'Batas tercapai'"
      :disabled="inputDisabled"
      class="flex-1 border-0 bg-transparent px-1 py-1 text-sm outline-none placeholder:text-muted-foreground"
    />

    <TagsInputClear
      v-if="tags().length"
      class="shrink-0 cursor-pointer p-1 text-muted-foreground hover:text-foreground"
      @click.stop
    >
      <X class="h-3.5 w-3.5" />
      <span class="sr-only">Hapus semua tag</span>
    </TagsInputClear>
  </TagsInputRoot>
</template>
